accounts/urls.py
from django.urls import path
# viewsモジュールをインポート
from . import views
# viewsモジュールをインポートしてauth_viewという名前で利用する
from django.contrib.auth import views as auth_views

# URLパターンを逆引きできるように名前を付ける
app_name = 'accounts'

# URLパターンを登録するための変数
urlpatterns = [
    # サインアップページのビューの呼び出し
    # 「http(s)://<ホスト名>/signup/」へのアクセスに対して、
    # viewsモジュールのSignUpViewをインスタンス化する
    path('signup/', views.SignUpView.as_view(), name='signup'),

    # サインアップ完了ページのビューの呼び出し
    # 「http(s)://<ホスト名>/signup_success/」へのアクセスに対して、
    # viewsモジュールのSignUpSuccessViewをインスタンス化する
    path('signup_success/', views.SignUpSuccessView.as_view(), name='signup_success'),

    # ログインページの表示
    # 「http(s)://<ホスト名>/login/」へのアクセスに対して、
    # django.contrib.auth.views.LoginViewをインスタンス化して
    # ログインページを表示する
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),

    # ログインアウトを実行
    # 「http(s)://<ホスト名>/logout/」へのアクセスに対して、
    # django.contrib.auth.views.LogoutViewをインスタンス化して
    # ログインアウトさせる
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
]

kouka2/urls.py
from django.urls import path
from . import views

# URLパターンを逆引きできるように名前を付ける
app_name = 'kouka2'

# URLパターンを登録する変数
urlpatterns = [
    # kouka2アプリへのアクセスはviewsモジュールのIndexViewを実行
    path('', views.IndexView.as_view(), name='index'),

    # 写真投稿ページのアクセスはviewsモジュールのCreatePhotoViewを実行
    path('post/', views.CreatePhotoView.as_view(), name='post'),

    # 投稿完了ページのアクセスはviewsモジュールのPostSuccessViewを実行
    path('post_done/',
         views.PostSuccessView.as_view(),
         name='post_done'),

    # カテゴリ1一覧ページ
    # photos1/<Categorysデーブルのid値>にマッチング
    # <int:category>は辞書{category: id値(int)}としてCategory1Viewに渡される
    path('photos1/<int:category1>',
         views.Category1View.as_view(),
         name = 'photos_cat1'
         ),
     # カテゴリ2一覧ページ
    # photos2/<Categorysデーブルのid値>にマッチング
    # <int:category>は辞書{category: id値(int)}としてCategory2Viewに渡される
    path('photos2/<int:category2>',
         views.Category2View.as_view(),
         name = 'photos_cat2'
         ),
     # カテゴリ3一覧ページ
    # photos3/<Categorysデーブルのid値>にマッチング
    # <int:category>は辞書{category: id値(int)}としてCategory3Viewに渡される
    path('photos3/<int:category3>',
         views.Category3View.as_view(),
         name = 'photos_cat3'
         ),

    # ユーザーの投稿一覧ページ
    # user-list/<ユーザーテーブルのid値>にマッチング
    # <int:user>は辞書{user: id値(int)}としてUserViewに渡される
    path('user-list/<int:user>',
         views.UserView.as_view(),
         name = 'user_list'
         ),

    # 詳細ページ
    # photo-detail/<Photo postsテーブルのid値>にマッチング
    # <int:pk>は辞書{pk: id値(int)}としてDetailViewに渡される
    path('photo-detail/<int:pk>',
         views.DetailView.as_view(),
         name = 'photo_detail'
         ),

    # マイページ
    # mypage/へのアクセスはMypageViewを実行
    path('mypage/', views.MypageView.as_view(), name = 'mypage'),

    # 投稿写真の削除
    # # photo/<Photo postsテーブルのid値>/delete/にマッチング
    # <int:pk>は辞書{pk: id値(int)}としてPhotoDeleteViewに渡される
    path('photo/<int:pk>/delete/',
         views.PhotoDeleteView.as_view(),
         name = 'photo_delete'
         ),

    # 属性ソートページ
    # element_sort/へのアクセスはElementViewを実行
    path('element_sort/', views.ElementSortView.as_view(), name = 'element_sort'),

    # マイページのカテゴリ1一覧ページ
    # my_photos1/<Categorysデーブルのid値>にマッチング
    # <int:category>は辞書{category: id値(int)}としてMyCategory1Viewに渡される
    path('my_photos1/<int:category1>',
         views.MyCategory1View.as_view(),
         name = 'my_photos1'
         ),

     # マイページのカテゴリ2一覧ページ
    # my_photos2/<Categorysデーブルのid値>にマッチング
    # <int:category>は辞書{category: id値(int)}としてMyCategory2Viewに渡される
    path('my_photos2/<int:category2>',
         views.MyCategory2View.as_view(),
         name = 'my_photos2'
         ),

     # マイページのカテゴリ3一覧ページ
    # my_photos3/<Categorysデーブルのid値>にマッチング
    # <int:category>は辞書{category: id値(int)}としてMyCategory3Viewに渡される
    path('my_photos3/<int:category3>',
         views.MyCategory3View.as_view(),
         name = 'my_photos3'
         ),

     
    # マイページの属性ソートページ
    # my_element_sort/へのアクセスはMyElementViewを実行
    path('my_element_sort/', views.MyElementSortView.as_view(), name = 'my_element_sort'),
     
    # 編集ページのアクセスはviewsモジュールのPhotoUpdateViewを実行
    path('photo/<int:pk>/update/', views.PhotoUpdateView.as_view(), name='photo_update'),

    # 編集完了ページのアクセスはviewsモジュールのUpdateSuccessViewを実行
    path('update_done/',
         views.UpdateSuccessView.as_view(),
         name='update_done'),

    # 昇順ソートページ
    # old_sort/へのアクセスはOldSortViewを実行
    path('old_sort/', views.OldSortView.as_view(), name = 'old_sort'),

    # マイページの昇順ソートページ
    # my_old_sort/へのアクセスはMyOldSortViewを実行
    path('my_old_sort/', views.MyOldSortView.as_view(), name = 'my_old_sort'),

    # トップページの昇順検索ページ
    # searchへのアクセスはSearchViewを実行
    path('search/', views.SearchView.as_view(), name = 'search'),

     # マイページの昇順検索ページ
    # my_serach/へのアクセスはMySerachViewを実行
    path('my_search/', views.MySearchView.as_view(), name = 'my_search'),

]

kouka2project/urls.py
from django.contrib import admin
from django.urls import path, include #include追加
# auth.viewsをインポートしてauth_viewという名前で利用する
from django.contrib.auth import views as auth_views
# settingsを追加
from django.conf import settings
# staticを追加
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    # kouka2.urlsへのURLパターン
    path('', include('kouka2.urls')),

    # accounts.urlsへのパターン
    path('', include('accounts.urls')),

    # パスワードリセットのためのURL
    # PasswordResetConfirmViewがプロジェクトのurls.pyを参照するのでここに記載
    # パスワードリセット申し込みページ
    path('password_reset/',
         auth_views.PasswordResetView.as_view(
            template_name = "password_reset.html"),
         name ='password_reset'),

    # メール送信完了ページ
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
            template_name = "password_reset_sent.html"),
         name ='password_reset_done'),

    # パスワードリセットページ
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(
            template_name = "password_reset_form.html"),
         name ='password_reset_confirm'),

    # パスワードリセット完了ページ
    path('reset/done',
         auth_views.PasswordResetCompleteView.as_view(
            template_name = "password_reset_done.html"),
         name ='password_reset_complete'),
]

# urlpatternsにmediaフォルダーのURLパターンを追加
urlpatterns += static(
    # MEDIA_URL = 'media/'
    settings.MEDIA_URL,
    # MEDIA_ROOTにリダイレクト
    document_root=settings.MEDIA_ROOT
    )

kouka2/views.py
from django.shortcuts import render
# django.views.genericからTemplateView、ListViewをインポート
from django.views.generic import TemplateView, ListView
# django.views.genericからCreateViewをインポート
from django.views.generic import CreateView
# django.urlsからreverse_lazyをインポート
from django.urls import reverse_lazy
# formsモジュールからPhotoPostFormをインポート
from .forms import PhotoPostForm
# method_decoratorをインポート
from django.utils.decorators import method_decorator
# login_requiredをインポート
from django.contrib.auth.decorators import login_required
# modelsモジュールからモデルPhotoPostをインポート
from .models import PhotoPost
# django.views.genericからDetailViewをインポート
from django.views.generic import DetailView
# django.views.genericからDeleteViewをインポート
from django.views.generic import DeleteView
# django.views.genericからUpdateViewをインポート
from django.views.generic import UpdateView

class IndexView(ListView):
    '''トップページのビュー
    '''
    # index.htmlをレンダリングする
    template_name = 'index.html'
    # モデルPhotoPostのオブジェクトにorder_by()を適用して
    # 投稿日時の降順で並べ替える
    queryset = PhotoPost.objects.order_by('-posted_at')
    # 1ページに表示するレコードの件数
    paginate_by = 12

# デコレーターにより、CreatePhotoViewへのアクセスはログインユーザーに限定される
# ログイン状態でなければsettings.pyのLOGIN_URLにリダイレクトされる
@method_decorator(login_required, name='dispatch')
class CreatePhotoView(CreateView):
    '''投稿写真ページのビュー
    
    PhotoPostFormで定義されているモデルとフィールドと連携して
    投稿データをデータベースに登録する
    
    Attributes:
        form_class: モデルとフィールドが登録されたフォームクラス
        template_name: レンダリングするテンプレート
        success_url: データベースへの登録完了後のリダイレクト先
    '''
    # forms.pyのPhotoPostFormをフォームクラスとして登録
    form_class = PhotoPostForm
    # レンダリングするテンプレート
    template_name = "post_photo.html"
    # フォームデータ登録完了後のリダイレクト先
    success_url = reverse_lazy('kouka2:post_done')

    def form_valid(self, form):
        '''CreateViewクラスのform_validをオーバーライド
        
        フォームのバリデーションを通過したときに呼ばれる
        フォームデータの登録をここで行う
        
        parameters:
            form(django.forms.Form):
                form_classに格納されているPhotoPostFormオブジェクト
        Return:
            HttpResponseRedirectオブジェクト
                スーパークラスのform_valid()の戻り値を返すことで、
                success_urlで設定されているURLにリダイレクトさせる
        '''
        # commit=FalseにしてPOSTされたデータを取得
        postdata = form.save(commit=False)
        # 投稿ユーザーのidを取得してモデルのuserフィールドに格納
        postdata.user = self.request.user
        # 投稿データをデータベースに登録
        postdata.save()
        # 戻り値はスーパークラスのform_valid()の戻り値(HttpResponseRedirect)
        return super().form_valid(form)

class PostSuccessView(TemplateView):
    '''投稿完了ページのビュー
    
    Attributes:
        template_name: レンダリングするテンプレート
    '''
    # post_success.htmlをレンダリングする
    template_name = 'post_success.html'

class Category1View(ListView):
    '''カテゴリ1ページのビュー
    
    Attributes
        template_name: レンダリングするテンプレート
        paginate_by: 1ページに表示するレコードの件数
    '''
    # index.htmlをレンダリングする
    template_name = 'index.html'
    # 1ページに表示するレコードの件数
    paginate_by = 12

    def get_queryset(self):
        '''クエリを実行する
        
        self.kwargsの取得が必要なため、クラス変数querysetではなく、
        get_queryset()のオーバーライドによりクエリを実行する
        
        Returns:
            クエリによって取得されたレコード
        '''
        # self.kwargsでキーワードの辞書を取得し、
        # categoryキーの値(Categorysテーブルのid)を取得
        category_id = self.kwargs['category1']
        # filter(フィールド名=id)で絞り込む
        categories = PhotoPost.objects.filter(
            category1=category_id).order_by('-posted_at')
        # クエリによって取得されたレコードを返す
        return categories

class Category2View(ListView):
    '''カテゴリ2ページのビュー
    
    Attributes
        template_name: レンダリングするテンプレート
        paginate_by: 1ページに表示するレコードの件数
    '''
    # index.htmlをレンダリングする
    template_name = 'index.html'
    # 1ページに表示するレコードの件数
    paginate_by = 12

    def get_queryset(self):
        '''クエリを実行する
        
        self.kwargsの取得が必要なため、クラス変数querysetではなく、
        get_queryset()のオーバーライドによりクエリを実行する
        
        Returns:
            クエリによって取得されたレコード
        '''
        # self.kwargsでキーワードの辞書を取得し、
        # categoryキーの値(Categorysテーブルのid)を取得
        category_id = self.kwargs['category2']
        # filter(フィールド名=id)で絞り込む
        categories = PhotoPost.objects.filter(
            category2=category_id).order_by('-posted_at')
        # クエリによって取得されたレコードを返す
        return categories

class Category3View(ListView):
    '''カテゴリ3ページのビュー
    
    Attributes
        template_name: レンダリングするテンプレート
        paginate_by: 1ページに表示するレコードの件数
    '''
    # index.htmlをレンダリングする
    template_name = 'index.html'
    # 1ページに表示するレコードの件数
    paginate_by = 12

    def get_queryset(self):
        '''クエリを実行する
        
        self.kwargsの取得が必要なため、クラス変数querysetではなく、
        get_queryset()のオーバーライドによりクエリを実行する
        
        Returns:
            クエリによって取得されたレコード
        '''
        # self.kwargsでキーワードの辞書を取得し、
        # categoryキーの値(Categorysテーブルのid)を取得
        category_id = self.kwargs['category3']
        # filter(フィールド名=id)で絞り込む
        categories = PhotoPost.objects.filter(
            category3=category_id).order_by('-posted_at')
        # クエリによって取得されたレコードを返す
        return categories

class UserView(ListView):
    '''ユーザー投稿一覧ページのビュー
    
    Attributes
        template_name: レンダリングするテンプレート
        paginate_by: 1ページに表示するレコードの件数
    '''
    # index.htmlをレンダリングする
    template_name = 'index.html'
    # 1ページに表示するレコードの件数
    paginate_by = 12

    def get_queryset(self):
        '''クエリを実行する
        
        self.kwargsの取得が必要なため、クラス変数querysetではなく、
        get_queryset()のオーバーライドによりクエリを実行する
        
        Returns:
            クエリによって取得されたレコード
        '''
        # self.kwargsでキーワードの辞書を取得し、
        # userキーの値(ユーザーテーブルのid)を取得
        user_id = self.kwargs['user']
        # filter(フィールド名=id)で絞り込む
        user_list = PhotoPost.objects.filter(
            user=user_id).order_by('-posted_at')
        # クエリによって取得されたレコードを返す
        return user_list

class DetailView(DetailView):
    '''詳細ページのビュー
    
    投稿記事の詳細を表示するのでDetailViewを継承する
    Attributes:
        template_name: レンダリングするテンプレート
        model: モデルのクラス
    '''
    # detail.htmlをレンダリングする
    template_name = 'detail.html'
    # クラス変数modelにPhotoPostを設定
    model = PhotoPost

class MypageView(ListView): 
    '''マイページのビュー
    
    Attributes
        template_name: レンダリングするテンプレート
        paginate_by: 1ページに表示するレコードの件数
    '''
    # mypage.htmlをレンダリングする
    template_name = 'mypage.html'
    # 1ページに表示するレコードの件数
    paginate_by = 12

    def get_queryset(self):
        '''クエリを実行する
        
        self.kwargsの取得が必要なため、クラス変数querysetではなく、
        get_queryset()のオーバーライドによりクエリを実行する
        
        Returns:
            クエリによって取得されたレコード
        '''
        # 現在ログインしているユーザー名はHttpRequest.userに格納されている
        # filter(userフィールド=userオブジェクト)で絞り込む
        queryset = PhotoPost.objects.filter(
            user=self.request.user).order_by('-posted_at')
        # クエリによって取得されたレコードを返す
        return queryset

class PhotoDeleteView(DeleteView):
    '''レコードの削除を行うビュー
    
    Attributes:
        model: モデル
        template_name: レンダリングするテンプレート
        paginate_by: 1ページに表示するレコードの件数
        success_url: 削除完了後のリダイレクト先のURL
    '''
    # 操作の対象はPhotoPostモデル
    model = PhotoPost
    # photo_delete.htmlをレンダリングする
    template_name = 'photo_delete.html'
    # 処理完了後にマイページにリダイレクト
    success_url = reverse_lazy('kouka2:mypage')

    def delete(self, request, *args, **kwargs):
        '''レコードの削除を行う
        
        Parameters:
            self: PhotoDeleteViewオブジェクト
            request: WSGIRequest(HttpRequest)オブジェクト
            args: 引数として渡される辞書(dict)
            kwargs: キーワード付きの辞書(dict)
                {'pk': 21}のようにレコードのidが渡される
                
        Returns:
            HttpResponseRedirect(success_url)を渡して
            success_urlにリダイレクト
        '''
        # スーパークラスのdelete()を実行
        return super().delete(request, *args, **kwargs)

class ElementSortView(ListView):
    '''属性ソートのビュー
    
    Attributes
        template_name: レンダリングするテンプレート
        paginate_by: 1ページに表示するレコードの件数
    '''
    # index.htmlをレンダリングする
    template_name = 'index.html'
    # 1ページに表示するレコードの件数
    paginate_by = 12

    def get_queryset(self):
        '''クエリを実行する
        
        self.kwargsの取得が必要なため、クラス変数querysetではなく、
        get_queryset()のオーバーライドによりクエリを実行する
        
        Returns:
            クエリによって取得されたレコード
        '''
        # 現在ログインしているユーザー名はHttpRequest.userに格納されている
        # filter(userフィールド=userオブジェクト)で絞り込む
        queryset = PhotoPost.objects.order_by('category1', '-posted_at')
        # クエリによって取得されたレコードを返す
        return queryset

class MyCategory1View(ListView):
    '''マイページのカテゴリ1ページのビュー
    
    Attributes
        template_name: レンダリングするテンプレート
        paginate_by: 1ページに表示するレコードの件数
    '''
    # mypage.htmlをレンダリングする
    template_name = 'mypage.html'
    # 1ページに表示するレコードの件数
    paginate_by = 12

    def get_queryset(self):
        '''クエリを実行する
        
        self.kwargsの取得が必要なため、クラス変数querysetではなく、
        get_queryset()のオーバーライドによりクエリを実行する
        
        Returns:
            クエリによって取得されたレコード
        '''
        # self.kwargsでキーワードの辞書を取得し、
        # categoryキーの値(Categorysテーブルのid)を取得
        category_id = self.kwargs['category1']
        # filter(フィールド名=id)で絞り込む
        categories = PhotoPost.objects.filter(
            category1=category_id, user=self.request.user).order_by('-posted_at')
        # クエリによって取得されたレコードを返す
        return categories

class MyCategory2View(ListView):
    '''マイページのカテゴリ2ページのビュー
    
    Attributes
        template_name: レンダリングするテンプレート
        paginate_by: 1ページに表示するレコードの件数
    '''
    # mypage.htmlをレンダリングする
    template_name = 'mypage.html'
    # 1ページに表示するレコードの件数
    paginate_by = 12

    def get_queryset(self):
        '''クエリを実行する
        
        self.kwargsの取得が必要なため、クラス変数querysetではなく、
        get_queryset()のオーバーライドによりクエリを実行する
        
        Returns:
            クエリによって取得されたレコード
        '''
        # self.kwargsでキーワードの辞書を取得し、
        # categoryキーの値(Categorysテーブルのid)を取得
        category_id = self.kwargs['category2']
        # filter(フィールド名=id)で絞り込む
        categories = PhotoPost.objects.filter(

kouka2/templates/photos_list.html
<section class="text-center">
    <div class="album py-5 bg-light">
        <!-- Bootstrapのグリッドシステムを適用 -->
        <div class="container">
            <br>
            {% url 'kouka2:photos_cat1' 1 as photos_cat1_1 %}
            {% url 'kouka2:photos_cat1' 2 as photos_cat1_2 %}
            {% url 'kouka2:photos_cat1' 3 as photos_cat1_3 %}
            {% url 'kouka2:photos_cat1' 4 as photos_cat1_4 %}
            {% url 'kouka2:photos_cat1' 5 as photos_cat1_5 %}
            {% url 'kouka2:photos_cat2' 1 as photos_cat2_1 %}
            {% url 'kouka2:photos_cat2' 2 as photos_cat2_2 %}
            {% url 'kouka2:photos_cat2' 3 as photos_cat2_3 %}
            {% url 'kouka2:photos_cat2' 4 as photos_cat2_4 %}
            {% url 'kouka2:photos_cat2' 5 as photos_cat2_5 %}
            {% url 'kouka2:photos_cat3' 1 as photos_cat3_1 %}
            {% url 'kouka2:photos_cat3' 2 as photos_cat3_2 %}
            {% url 'kouka2:element_sort' as element_sort %}
            {% url 'kouka2:index' as new_sort %}
            {% url 'kouka2:old_sort' as old_sort %}
            {% url 'kouka2:my_photos1' 1 as my_photos1_1 %}
            {% url 'kouka2:my_photos1' 2 as my_photos1_2 %}
            {% url 'kouka2:my_photos1' 3 as my_photos1_3 %}
            {% url 'kouka2:my_photos1' 4 as my_photos1_4 %}
            {% url 'kouka2:my_photos1' 5 as my_photos1_5 %}
            {% url 'kouka2:my_photos2' 1 as my_photos2_1 %}
            {% url 'kouka2:my_photos2' 2 as my_photos2_2 %}
            {% url 'kouka2:my_photos2' 3 as my_photos2_3 %}
            {% url 'kouka2:my_photos2' 4 as my_photos2_4 %}
            {% url 'kouka2:my_photos2' 5 as my_photos2_5 %}
            {% url 'kouka2:my_photos3' 1 as my_photos3_1 %}
            {% url 'kouka2:my_photos3' 2 as my_photos3_2 %}
            {% url 'kouka2:my_element_sort' as my_element_sort %}
            {% url 'kouka2:mypage' as my_new_sort %}
            {% url 'kouka2:my_old_sort' as my_old_sort %}
            {% if object_list.count == 0 %}
                <h3>投稿はありません</h3>
            {% elif request.path == photos_cat1_1 %}
                <h3>火属性一覧</h3>
            {% elif request.path == photos_cat1_2 %}
                <h3>水属性一覧</h3>
            {% elif request.path == photos_cat1_3 %}
                <h3>木属性一覧</h3>
            {% elif request.path == photos_cat1_4 %}
                <h3>光属性一覧</h3>
            {% elif request.path == photos_cat1_5 %}
                <h3>闇属性一覧</h3>
            {% elif request.path == photos_cat2_1 %}
                <h3>進化前一覧</h3>
            {% elif request.path == photos_cat2_2 %}
                <h3>進化/神化一覧</h3>
            {% elif request.path == photos_cat2_3 %}
                <h3>獣神化一覧</h3>
            {% elif request.path == photos_cat2_4 %}
                <h3>獣神化・改一覧</h3>
            {% elif request.path == photos_cat2_5 %}
                <h3>真獣神化一覧</h3>
            {% elif request.path == photos_cat3_1 %}
                <h3>ガチャキャラ一覧</h3>
            {% elif request.path == photos_cat3_2 %}
                <h3>その他キャラ一覧</h3>
            {% elif request.path == element_sort %}
                <h3>属性順</h3>
            {% elif request.path == new_sort %}
                <h3>新しい順</h3>
            {% elif request.path == old_sort %}
                <h3>古い順</h3>
            {% elif request.path == my_photos1_1 %}
                <h3>火属性一覧</h3>
            {% elif request.path == my_photos1_2 %}
                <h3>水属性一覧</h3>
            {% elif request.path == my_photos1_3 %}
                <h3>木属性一覧</h3>
            {% elif request.path == my_photos1_4 %}
                <h3>光属性一覧</h3>
            {% elif request.path == my_photos1_5 %}
                <h3>闇属性一覧</h3>
            {% elif request.path == my_photos2_1 %}
                <h3>進化前一覧</h3>
            {% elif request.path == my_photos2_2 %}
                <h3>進化/神化一覧</h3>
            {% elif request.path == my_photos2_3 %}
                <h3>獣神化一覧</h3>
            {% elif request.path == my_photos2_4 %}
                <h3>獣神化・改一覧</h3>
            {% elif request.path == my_photos2_5 %}
                <h3>真獣神化一覧</h3>
            {% elif request.path == my_photos3_1 %}
                <h3>ガチャキャラ一覧</h3>
            {% elif request.path == my_photos3_2 %}
                <h3>その他キャラ一覧</h3>
            {% elif request.path == my_element_sort %}
                <h3>属性順</h3>
            {% elif request.path == my_new_sort %}
                <h3>新しい順</h3>
            {% elif request.path == my_old_sort %}
                <h3>古い順</h3>                 
            {% endif %}
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">  
                {% for record in object_list %}
                <section class="py-5 text-center container">
                    <div class="col">
                        <!-- Blog post-->
                        <div class="card shadow-sm">
                            <a href="{% url 'kouka2:photo_detail' record.pk %}"><img class="card-img-top" src="{{ record.title_image.url }}" alt="..." width="400" height="350"/></a>
                            <div class="card-body">
                                <div class="small text-muted">{{record.posted_at}}に投稿>>>>>
                                    <a href="{% url 'kouka2:user_list' user=record.user.id %}">
                                        <small class="text-muted">
                                            {{record.user.username}}</small>
                                    </a>
                                </div>
                            <h2 class="card-title h4">
                                <!-- titleフィールドを出力 -->
                                {{record.title}}
                            </h2>
                            <a class="btn btn-primary" href="{% url 'kouka2:photo_detail' record.pk %}">詳細</a>
                            <a class="btn btn-outline-secondary" href="{% url 'kouka2:photos_cat1' category1=record.category1.id %}">
                                {{record.category1.title}}</a>
                            <a class="btn btn-outline-secondary" href="{% url 'kouka2:photos_cat2' category2=record.category2.id %}">
                                {{record.category2.title}}</a>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- forブロック終了 -->
                {% endfor %}
            </div>
        <!-- グリッドシステムここまで -->
        </div>
    </div>
</section>

kouka2/templates/photos_title.html
<!-- タイトルとナビゲーションボタン -->
<section class="mt-5 text-center container">
    <div class="row py-lg-1">
        <div class="col-lg-6 col-md-8 mx-auto">
            <!-- タイトルと本文 -->
            <h1 class="fw-bolder">モンスト図鑑</h1>
            <p class="lead mb-0">モンストのキャラのステータスやプロフィールが見れる図鑑です<br>好きなキャラや投稿したいキャラがいれば、ぜひ投稿してください</p>
            <P>
                <!-- ナビゲーションボタン -->
                {% if user.is_authenticated %}
                <!-- ログイン中のボタン -->
                <a href="{% url 'kouka2:post' %}" class="btn btn-primary my-2">投稿する</a>
                <a href="{% url 'accounts:logout' %}" class="btn btn-secondary my-2">ログアウト</a>
                {% else %}
                <!-- ログイン状態ではない場合のボタン -->
                <a href="{% url 'accounts:signup' %}" class="btn btn-primary my-2">今すぐサインアップ</a>
                <a href="{% url 'accounts:login' %}" class="btn btn-secondary my-2">登録済みの方はログイン</a>
                {% endif %}
                
            </p>
        </div>
    </div>
</section>